# Generated by Django 2.1.5 on 2019-02-20 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('choices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishMeaning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.TextField(blank=True, null=True, verbose_name='Meaning')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('part_of_speech', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='choices.PartOfSpeech', verbose_name='Part of Speech')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnglishWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True, verbose_name='word')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['word'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='YorubaMeaning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.TextField(blank=True, null=True, verbose_name='Meaning')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('part_of_speech', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='choices.PartOfSpeech', verbose_name='Part of Speech')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='YorubaWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True, verbose_name='word')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('english_equivalents', models.ManyToManyField(to='lexicons.EnglishMeaning')),
            ],
            options={
                'ordering': ['word'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='yorubameaning',
            name='words',
            field=models.ManyToManyField(to='lexicons.YorubaWord'),
        ),
        migrations.AddField(
            model_name='englishmeaning',
            name='words',
            field=models.ManyToManyField(to='lexicons.EnglishWord'),
        ),
    ]
